### ISSUE TITLE
Role metadata error

### ISSUE THREAD

**Issue by zumo64** [AlbanAndrieu/ansible-jmeter#2]
Hi 
With ansible 2.1.0.0  I am getting this error :

ERROR! 'ansigenome_info' is not a valid attribute for a RoleMetadata

The error appears to have been in '/private/etc/ansible/roles/alban.andrieu.jmeter/meta/main.yml': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---

dependencies: []
^ here
##

**Comment by harish-vallabhaneni** [comment]
Hi @zumo64. Were you able to resolve that issue. I'm getting the same error.
@AlbanAndrieu can you please look into this error.

when i do --> ansible-playbook jmeter.yml --private-key=/path/to/.pem , I'm getting the following error:
 
ERROR! 'ansigenome_info' is not a valid attribute for a RoleMetadata

The error appears to have been in '/private/etc/ansible/roles/alban.andrieu.jmeter/meta/main.yml': line 2, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
dependencies: []
^ here

**Comment by jwgcooke** [comment]
I am seeing this as well...

**Comment by AlbanAndrieu** [comment]
Can you try with master branch.
Issue might come from the fact that in https://github.com/AlbanAndrieu/ansible-jmeter/blob/master/meta/main.yml there is an ansigenome information and since ansible 2.1 it failed.
On master I have moved information in file https://github.com/AlbanAndrieu/ansible-jmeter/blob/master/meta/ansigenome.yml
Ansigenome is for automatic README generation so it can be skip. It is not mandatory at all.
